version: '2'
services:
    engine:
        image: picshape/picshape-engine:latest
        ports:
            - "8080:8080"


    front:
        image: picshape/picshape-front:latest
        ports:
            - "80:3000"

        depends_on:
            - engine
